language: php
dist: trusty
sudo: required
addons:
  chrome: stable

env:
  global:
    - CHROME_PATH="google-chrome-stable"

matrix:
  include:
  - php: 7.1
  - php: 7.2
  - php: 7.3
  - php: 7.4
    env: PROCESS_CODECLIMATE=true
  - php: hhvm
    env: IGNORE_XDEBUG=true

  fast_finish: true

  allow_failures:
  - php: hhvm

before_script:
  - if [ -z "$IGNORE_XDEBUG" ];then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update
  - travis_retry composer update --prefer-dist --ignore-platform-reqs
  - if [ -n "$PROCESS_CODECLIMATE" ];then echo 'zend_extension=xdebug.so' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi

script: ./test/bin/ci.bash summary

cache:
  directories:
    - $HOME/.composer/cache
